/**
 * Phase 4 AuditTrail — Checklist D7: action types (extensible).
 * Do not remove values; add new ones for new audited actions.
 */
export const AuditActionType = {
  DOC_CREATE_DRAFT: 'DOC_CREATE_DRAFT',
  DOC_UPDATE_DRAFT: 'DOC_UPDATE_DRAFT',
  DOC_FINALIZE: 'DOC_FINALIZE',
  DOC_CREATE_CORRECTION: 'DOC_CREATE_CORRECTION',
  DOC_ANULATE: 'DOC_ANULATE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  SESSION_UNLOCK_SUCCESS: 'SESSION_UNLOCK_SUCCESS',
  SESSION_UNLOCK_FAIL: 'SESSION_UNLOCK_FAIL',
  ADMIN_ROLES_PERMISSIONS: 'ADMIN_ROLES_PERMISSIONS',
  ADMIN_USER_ASSIGNMENTS: 'ADMIN_USER_ASSIGNMENTS',
  ADMIN_CONFIG_SIRES: 'ADMIN_CONFIG_SIRES',
  SYSTEM_JOB: 'SYSTEM_JOB',
  GIIS_EXPORT_STARTED: 'GIIS_EXPORT_STARTED',
  GIIS_EXPORT_FILE_GENERATED: 'GIIS_EXPORT_FILE_GENERATED',
  GIIS_EXPORT_DOWNLOADED: 'GIIS_EXPORT_DOWNLOADED',
  GIIS_VALIDATION_EXECUTED: 'GIIS_VALIDATION_EXECUTED',
  AUDIT_EXPORT_DOWNLOAD: 'AUDIT_EXPORT_DOWNLOAD',
  // Phase 5: user management and signer profiles
  USER_INVITATION_SENT: 'USER_INVITATION_SENT',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_DELETED: 'USER_DELETED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  SIGNER_PROFILE_CREATED: 'SIGNER_PROFILE_CREATED',
  SIGNER_PROFILE_UPDATED: 'SIGNER_PROFILE_UPDATED',
} as const;

export type AuditActionTypeValue =
  (typeof AuditActionType)[keyof typeof AuditActionType];
